### ISSUE TITLE
Error: data too large for key size

### ISSUE THREAD

**Issue by tlvince** [singapore/renovate-encrypt#2]
Using a private npm registry ([jFrog Artifactory](https://jfrog.com/artifactory/)), I'm getting:

```
❯ /tmp/node_modules/.bin/renovate-encrypt < ~/.npmrc
(node:97393) UnhandledPromiseRejectionWarning: Error: error:040A006E:rsa routines:RSA_padding_add_PKCS1_OAEP_mgf1:data too large for key size
    at Object.publicEncrypt (crypto.js:390:12)
    at ReadStream.<anonymous> (/private/tmp/node_modules/renovate-encrypt/dist/renovate-encrypt.js:22:28)
    at Generator.next (<anonymous>)
    at step (/private/tmp/node_modules/renovate-encrypt/dist/renovate-encrypt.js:2:191)
    at /private/tmp/node_modules/renovate-encrypt/dist/renovate-encrypt.js:2:437
    at new Promise (<anonymous>)
    at ReadStream.<anonymous> (/private/tmp/node_modules/renovate-encrypt/dist/renovate-encrypt.js:2:99)
    at emitNone (events.js:111:20)
    at ReadStream.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
(node:97393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:97393) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The auth token generated (via `npm login`) is much longer (859) characters than the public registry. Will this make a difference? Also Artefactory does not appear to support `npm token`, e.g.:

```shell
❯ npm token list
npm ERR! code E404
npm ERR! 404 Registry returned 404 for undefined on https://example.jfrog.io/example/api/npm/npm/-/npm/v1/tokens
```

**Comment by rarkins** [comment]
@tlvince could you try this approach:

1. Instead of encrypting the `.npmrc` file, instead copy/paste it into `config.npmrc` replacing newlines with `\n` in the string
2. Encrypt the token *alone* and add it to `config.encrypted.token`
3. Replace the token string in `config.npmrc` with `${NPM_TOKEN}` instead

So your config would look something like:

```json
{
  "npmrc": "foo=bar\nregistry=blah blah\n_auth=${NPM_TOKEN}",
  "encrypted": {
    "npmToken": "xxT19RIdhAh09lkhdrK39HzKNBn3etoLZAwHdeJ25cX+5y52a9kAC7flXmdw5JrkciN08aQuRNqDaKxp53IVptB5AYOnQPrt8MCT+x0zHgp4A1zv1QOV84I6uugdWpFSjPUkmLGMgULudEZJMlY/dAn/IVwf/IImqwazY8eHyJAA4vyUqKkL9SXzHjvS+OBonQ/9/AHYYKmDJwT8vLSRCKrXxJCdUfH7ZnikZbFqjnURJ9nGUHP44rlYJ7PFl05RZ+X5WuZG/A27S5LuBvguyQGcw8A2AZilHSDta9S/4eG6kb22jX87jXTrT6orUkxh2WHI/xvNUEout0gxwWMDkA=="
  }
}
```

**Comment by tlvince** [comment]
Thanks. I tried encrypting the token in isolation, but ran into the same issue. Here's an example (sanitised) token if you'd like to try:

```
p0KnZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJsNVJ1VU4yV3NmZVhzdy1BSHNqNUw1bGFEZVpDTUZZOWM4UnRGcjB0Y0JnIn0.eyJzdWIiOiJqZi1hcnRpZmFjdG9yeUBlY2M5MjhiOS1kMjk1LTQyOTktOGU4Zi01MjlmZTJkMGRjYjBcL3VzZXJzXC90b20udmluY2VudCIsInNjcCI6Im1lbWJlci1vZi1ncm91cHM6KiBhcGk6KiIsImF1ZCI6ImpmLWFydGlmYWN0b3J5QGVjYzkyOGI5LWQyOTUtN9I5OS04ZThmLTUyOWZlMmQwZGNiMCIsImlzcyI6ImpmLWFydGlmYWN0b3J5QGVjYzkyOGI5LWQyOTUtlDI5OS04ZThmLTUyOWZlMmQwZGNiMCIsImlhdCI6MTUzMTIxNTIzNiwianRpIjoiMTg0Zjc3YTYtYmUy1P03MGE3LWEyYzQtOTc0ZDg3NDUyMDg2In0.Fewf1g3kTLDV2_P04iaC3PcsWu7UBUz4JcCZggni4W5A-fsOAGtDmPL6RxPVHaPX3pEzR5RgpC88e0k_yBKDxZZ2esN9JeRYVYeFnOdTu7TsC0RofS5AAJM2uhU_Tx8saGPDXpwMIRAZWVyQmfWWjrpAw_xF6TxjdKxLuPKw2aHrC3aDiz7AP28xgW0wD6s8icdYg5og16_LEfvbbw38rZPxST4I0AIUZq8SOF6rR1XArBS09B4K2aM9_DULamQCzQQSNZKmH9R-gCNCEmUVLitA3VCQX47D4Fqyxhjg7ZL0Nas-vuzNyu9OfwakyKStXAWvEa_MlASINk0ufz0_1q
```

**Comment by rarkins** [comment]
Sorry I haven't seen tokens that long before. The public/private key encryption approach unfortunately has a limit to how long a string can be. Is it possible that your Artifactory supports Basic authentication instead? e.g. https://jfrog.com/knowledge-base/how-to-authenticate-against-artifactory-with-a-http-rest-client/

**Comment by tlvince** [comment]
It does, yes. I'll close this for now. Thanks!
